version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          docker:
            - image: circleci/node:latest
          steps:
            - checkout:
                always: true
            - run:
                name: Deploy to Namecheap
                command: |
                  ssh -i "$SSH_PRIVATE_KEY" adonyype@67.223.118.123
                  cd /home/adonyype/public_html
                  git pull origin main