on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_adonai
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Connect and Pull
      run: ssh -i ~/.ssh/id_adonai ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/adonyype/public_html && git reset --hard && git clean -fd && git pull origin main && exit"

    - name: cleanup
      run: rm -rf ~/.ssh
