on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh
        printf "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        echo "SSH keys and known_hosts set up successfully."
      
    - name: Verify SSH Connection
      run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo Connection Successful!"

    - name: Pull Latest Changes
      run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd /home/adonyype/public_html && git checkout ${{ secrets.MAIN_BRANCH }} && git pull"

    - name: Cleanup SSH
      run: rm -rf ~/.ssh
